default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  username: postgres
  password: ''

development:
  <<: *default
  database: egift-dev
test:
  <<: *default
  database: egift-test